sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "6"
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - travis_wait 15 yarn run global

install:
  - travis_wait 15 yarn install

before_script:
  - travis_wait 20 yarn run build
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - travis_wait 20 yarn run ci
