sudo: required
dist: trusty

env:
  COMPOSE_VERSION: 1.24.1
  DSPACE_REST_HOST: localhost
  DSPACE_REST_PORT: 8080
  DSPACE_REST_NAMESPACE: '/server/api'
  DSPACE_REST_SSL: false

before_install:
  # Docker Compose Install
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - git clone https://github.com/DSpace-Labs/DSpace-Docker-Images.git

install:
  - docker-compose version
  - docker-compose -f DSpace-Docker-Images/docker-compose-files/dspace-compose/d7.travis.yml up -d
  - travis_retry yarn install
  # allow starup time
  #- sleep 60

before_script:
  # Startup the app
  #- curl http://localhost:8080/

after_script:
  - docker-compose -f DSpace-Docker-Images/docker-compose-files/dspace-compose/d7.travis.yml down

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "8"
  - "10"

cache:
  yarn: true

bundler_args: --retry 5

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - yarn run build
  - yarn run ci
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
