sudo: required
dist: trusty

env:
  COMPOSE_VERSION: 1.24.1

before_install:
  # Docker Compose Install
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # Download and install Docker libs
  - curl -L https://github.com/Ortus-Solutions/docker-buildfiles/archive/master.zip > docker.zip
  - unzip docker.zip -d workbench
  - mv workbench/docker-buildfiles-master workbench/docker
  # CommandBox Keys
  - sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a
    /etc/apt/sources.list.d/commandbox.list
  - curl -L https://github.com/DSpace-Labs/DSpace-Docker-Images/archive/master.zip > master.zip
  - unzip master.zip

install:
  # Core testing install
  - sudo apt-get update && sudo apt-get --assume-yes install commandbox
  - box install
  - box server start
  # Docker CFML Server Tests
  - export ANGULAR_SRC=$(pwd)
  - cd DSpace-Docker-Images/docker-compose-files/dspace-compose
  - docker-compose -f docker-compose.yml -f d7.override.yml -f agn-src-override.yml build
  - docker-compose -f docker-compose.yml -f d7.override.yml -f agn-src-override.yml -f load.entities.yml up -d

before_script:
  # Startup the app
  - curl http://localhost:8080/
  - curl http://localhost:3000/

after_script:
  - docker-compose -f docker-compose.yml -f d7.override.yml -f agn-src-override.yml down

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "8"
  - "10"

cache:
  yarn: true

bundler_args: --retry 5

install:
  - travis_retry yarn install

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - yarn run build
  - yarn run ci
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
